// Función para mostrar la ventana modal con la imagen y el texto correspondiente
function mostrarModal(imagenSrc, texto) {
    // Obtiene la ventana modal, la imagen y el texto dentro de ella
    var modal = document.getElementById("modal");
    var modalImage = document.getElementById("modal-image");
    var modalText = document.getElementById("modal-text");

    // Establece la imagen recibida como contenido de la ventana modal
    modalImage.src = imagenSrc;

    // Divide el texto en párrafos
    var paragraphs = texto.split("\n");

    // Crea elementos de párrafo para cada línea de texto
    modalText.innerHTML = "";
    paragraphs.forEach(function (paragraphText) {
        var paragraph = document.createElement("p");
        paragraph.innerHTML = paragraphText; // Utiliza innerHTML en lugar de textContent
        modalText.appendChild(paragraph);
    });

    // Muestra la ventana modal
    modal.style.display = "block";

    // Obtiene el botón de cierre y añade un evento de clic para cerrar la ventana modal
    var closeBtn = document.getElementsByClassName("close")[0];
    closeBtn.onclick = function () {
        modal.style.display = "none";
    }
}


// Asocia la función mostrarModal a cada enlace, pasando la imagen correspondiente como argumento
document.getElementById('amistad').addEventListener('click', function (event) {
    event.preventDefault();
    mostrarModal('img/amistad solida.jpg', 'Mantener una amistad sólida requiere esfuerzo, compromiso y comunicación constante. La clave está en tener una comunicación abierta y honesta, donde puedas expresar tus sentimientos, inquietudes y expectativas de manera sincera.\n\nAdemás, es importante escuchar activamente a tu amigo/a, mostrándole interés genuino y empatía hacia sus preocupaciones y alegrías.\n\nEl apoyo mutuo juega un papel fundamental en una amistad sólida. Estar ahí para tu amigo/a en los momentos difíciles, brindarle apoyo emocional y ofrecer ayuda práctica fortalece los lazos.\n\nTambién es esencial respetar y aceptar a tu amigo/a tal como es, valorando su individualidad y respetando sus opiniones, creencias y decisiones.\n\nDedicar tiempo de calidad juntos es otra clave importante. Planifica actividades que ambos disfruten, como salir a caminar, ver una película o simplemente pasar tiempo conversando. La constancia en estas interacciones ayuda a fortalecer la amistad.\n\nAdemás, es necesario practicar la comprensión y el perdón. Todos cometemos errores y tenemos momentos difíciles, por lo que es importante aprender a resolver conflictos de manera constructiva y buscar soluciones que satisfagan a ambas partes.\n\nMantener un contacto regular también es fundamental. Aunque la vida puede ser ocupada, trata de mantener una comunicación constante, ya sea a través de llamadas, mensajes o encuentros en persona. La consistencia en el contacto ayuda a mantener viva la amistad.');
});

document.getElementById('pareja').addEventListener('click', function (event) {
    event.preventDefault();
    mostrarModal('img/mejorar relacion.jpg', '<p><strong>Comunicación abierta y honesta:</strong> Habla con tu pareja sobre tus sentimientos, preocupaciones y expectativas de manera sincera y respetuosa. Escucha activamente lo que tienen que decir y trata de entender su perspectiva.</p>\n\n<p><strong>Practicar la empatía:</strong> Intenta ponerte en el lugar de tu pareja y comprender sus emociones y puntos de vista, incluso cuando no estés de acuerdo. La empatía fortalece el vínculo emocional y fomenta la comprensión mutua.</p>\n\n<p><strong>Respeto mutuo:</strong> Trata a tu pareja con respeto en todo momento, incluso durante los desacuerdos. Evita insultos, críticas destructivas o comportamientos irrespetuosos que puedan dañar la relación.</p>\n\n<p><strong>Tiempo de calidad juntos:</strong> Dedica tiempo a actividades compartidas que disfruten ambos, ya sea salir a cenar, ver una película, practicar deportes o simplemente pasar tiempo juntos en casa. Estas experiencias fortalecen el vínculo afectivo.</p>\n\n<p><strong>Espacio personal:</strong> Aunque es importante pasar tiempo juntos, también es fundamental respetar el espacio personal de cada uno. Permitan que cada uno tenga tiempo para sí mismo y para mantener sus propios intereses y hobbies.</p>\n\n<p><strong>Resolver conflictos de manera constructiva:</strong> Los conflictos son normales en cualquier relación, pero es importante abordarlos de manera constructiva y buscar soluciones juntos en lugar de culpar o atacar al otro.');

});

document.getElementById('familia').addEventListener('click', function (event) {
    event.preventDefault();
    mostrarModal('img/construyendo familias.jpg', '<p>Construir relaciones familiares saludables es fundamental para el bienestar emocional y el desarrollo de todos los miembros de la familia. Aquí hay algunos aspectos clave para lograrlo:</p>\n\n<p><strong>Comunicación abierta y respetuosa:</strong> Fomenta un ambiente donde todos los miembros de la familia se sientan seguros para expresar sus pensamientos, sentimientos y preocupaciones. Escucha activamente a cada miembro y valora sus opiniones, incluso si difieren de las tuyas.</p>\n\n<p><strong>Pasar tiempo juntos de calidad:</strong> Dedica tiempo regularmente para actividades en familia, como cenas, salidas al aire libre, juegos de mesa o simplemente conversar. Estos momentos fortalecen los lazos familiares y crean recuerdos duraderos.</p>\n\n<p><strong>Establecer límites y normas claras:</strong> Define reglas y límites que sean adecuados para la edad y las necesidades de cada miembro de la familia. Asegúrate de que todos comprendan estas normas y las razones detrás de ellas, y sé consistente en hacer que se cumplan.</p>\n\n<p><strong>Resolver conflictos de manera constructiva:</strong> Los conflictos son inevitables en cualquier relación, pero es importante abordarlos de manera respetuosa y buscar soluciones juntos. Enseña a los miembros de la familia habilidades de resolución de problemas y promueve el perdón y la reconciliación.</p>\n\n<p><strong>Fomentar el apoyo mutuo:</strong> Anime a los miembros de la familia a apoyarse entre sí en tiempos difíciles y a celebrar los éxitos y logros de cada uno.');
});

document.getElementById('conflictos').addEventListener('click', function (event) {
    event.preventDefault();
    mostrarModal('img/solucion de conflictos.jpg', '<p>Lidiar con conflictos familiares puede ser desafiante, pero es posible manejarlos de manera constructiva. Aquí tienes algunas estrategias que pueden ayudarte a abordar los conflictos familiares de manera efectiva:</p>\n\n<p><strong>Mantén la calma:</strong> Enfrenta el conflicto con una actitud calmada y controlada. Evita reaccionar impulsivamente o responder con ira, ya que esto puede empeorar la situación.</p>\n\n<p><strong>Escucha activamente:</strong> Presta atención a lo que cada miembro de la familia tiene que decir sin interrumpir. Practica la escucha activa, reflejando lo que han dicho para demostrar que comprendes sus sentimientos y perspectivas.</p>\n\n<p><strong>Expresa tus sentimientos de manera asertiva:</strong> Comunica tus propios sentimientos y preocupaciones de manera clara y respetuosa. Utiliza "yo" en lugar de "tú" para evitar culpar o acusar a los demás.</p>\n\n<p><strong>Busca puntos en común:</strong> Identifica áreas de acuerdo o intereses compartidos que puedan servir como base para la resolución del conflicto. Enfócate en encontrar soluciones que beneficien a todos los involucrados.</p>\n\n<p><strong>Busca el momento y el lugar adecuados:</strong> Elige un momento y un lugar adecuados para discutir el conflicto, preferiblemente en privado y cuando todos estén calmados y dispuestos a escuchar.</p>\n\n<p><strong>Practica el respeto mutuo:</strong> Trata a los demás con respeto y dignidad, incluso durante el conflicto. Evita insultos, críticas destructivas o comportamientos agresivos que puedan dañar la relación.</p>\n\n<p><strong>');
});

document.getElementById('autoestima').addEventListener('click', function (event) {
    event.preventDefault();
    mostrarModal('img/aumentando la autoestima.jpg', '<p>La autoestima es la valoración que tenemos de nosotros mismos. Construir una autoestima positiva implica aceptarse a uno mismo, reconocer nuestras fortalezas y trabajar en áreas de mejora.</p>\n\n<p><strong>Reconocer los puntos fuertes y logros personales:</strong> Pasa tiempo enfocándote en todo lo que has hecho bien en lugar de en tus debilidades.</p>\n\n<p><strong>Practicar autosobrecargar positiva:</strong> En lugar de hablar contigo mismo de forma crítica, reemplaza esos pensamientos con frases positivas que te hagan sentir bien.</p>\n\n<p><strong>Centrarse en los aspectos internos en lugar de externos:</strong> La apariencia física o lo que poseen los demás no define tu valor. Enfócate en quien eres por dentro.</p>\n\n<p><strong>Hacer ejercicio de forma regular:</strong> La actividad física beneficia la salud mental al liberar endorfinas que generan bienestar.</p>\n\n<p><strong>Pasar tiempo con gente positiva:</strong> Aléjate de las relaciones tóxicas y rodearte de personas que te apoyen y hagan sentir bien.</p>\n\n<p><strong>Aprender a aceptar los errores:</strong> Todos nos equivocamos, el éxito está en aprender de ellos en vez de culparse.</p>\n\n<p><strong>Realizar pequeños logros a diario:</strong> Alcanzar pequeñas metas que dependan solo de ti te dará un sentimiento de realización.</p>\n\n<p><strong>Practicar actividades significativas:</strong> Encontrar pasatiempos y causas que te apasionen y den propósito a tu vida.</p>\n\n<p><strong>Buscar ayuda si es necesario:</strong> No dudes en consultar a un profesional si sientes que tu autoestima está realmente afectada.</p>');
});

document.getElementById('superar_inseguridad').addEventListener('click', function (event) {
    event.preventDefault();
    mostrarModal('img/superando inseguridades.jpg', '<p>La inseguridad puede manifestarse de diversas formas y afectar diferentes aspectos de la vida, como las relaciones interpersonales, el trabajo o el bienestar emocional. Puede surgir debido a experiencias pasadas, comparaciones con los demás, expectativas poco realistas o creencias negativas sobre uno mismo. La inseguridad puede limitar tu capacidad para alcanzar tus metas y disfrutar plenamente de la vida.</p>\n\n<p><strong>Sin embargo, es posible superar la inseguridad y desarrollar una mayor confianza en ti mismo.</strong> Este proceso implica explorar las causas subyacentes de tus sentimientos de inseguridad, cambiar tus patrones de pensamiento negativo y desarrollar una relación más compasiva y amorosa contigo mismo.</p>\n\n<p><strong>Al trabajar en tu autoestima y aceptarte a ti mismo de manera más completa, puedes comenzar a experimentar una mayor sensación de seguridad y satisfacción en tu vida.</strong> A través de prácticas como el autocuidado, la autocompasión y el establecimiento de metas realistas, puedes aprender a valorarte a ti mismo y confiar en tus habilidades y capacidades.</p>\n\n<p><strong>Identifica tus pensamientos negativos:</strong> Presta atención a los pensamientos negativos y autocríticos que puedan estar contribuyendo a tu inseguridad. Identifica patrones de pensamiento irracionales o poco realistas y trabaja en desafiar y cambiar estos pensamientos.</p>\n\n<p><strong>Cambia tu diálogo interno:</strong> Reemplaza los pensamientos negativos por afirmaciones positivas y realistas sobre ti mismo. Practica el autoaprecio y la autocompasión, reconociendo tus fortalezas y logros en lugar de enfocarte solo en tus debilidades.</p>\n\n<p><strong>Desafía tus miedos:</strong> Enfrenta gradualmente tus miedos y sal de tu zona de confort. Establece metas realistas y alcanzables que te permitan enfrentar tus temores de manera controlada y gradual.</p>\n\n<p><strong>');
});

document.getElementById('estres').addEventListener('click', function (event) {
    event.preventDefault();
    mostrarModal('img/estrategias estres.jpg', '<p><strong>Respiración profunda:</strong> Practica ejercicios de respiración profunda para calmar el sistema nervioso y reducir la ansiedad. Inhala lenta y profundamente por la nariz, sintiendo cómo se expande tu abdomen, y exhala lentamente por la boca.</p>\n\n<p><strong>Meditación y mindfulness:</strong> Dedica tiempo a la meditación y la práctica del mindfulness para cultivar la atención plena en el momento presente. Esto puede ayudarte a reducir el estrés y la rumiación mental, y a aumentar la claridad mental y la calma.</p>\n\n<p><strong>Ejercicio físico regular:</strong> Realiza actividad física regularmente, ya sea caminar, correr, practicar yoga, nadar o cualquier otra actividad que disfrutes. El ejercicio libera endorfinas, neurotransmisores que mejoran el estado de ánimo, y reduce los niveles de estrés.</p>\n\n<p><strong>Establece límites:</strong> Aprende a decir "no" cuando sea necesario y establece límites saludables en tus relaciones y actividades. Prioriza tus propias necesidades y no te sobrecargues de responsabilidades.</p>\n\n<p><strong>Organización y planificación:</strong> Organiza tu tiempo y tus tareas de manera efectiva utilizando agendas, listas de tareas y otras herramientas de planificación. Esto puede ayudarte a sentirte más en control y a reducir el estrés relacionado con la sensación de abruma.</p>\n\n<p><strong>Practica el autocuidado:</strong> Dedica tiempo a cuidar de ti mismo haciendo actividades que te gusten y te relajen, como leer, tomar un baño caliente, escuchar música, dibujar o practicar hobbies.</p>\n\n<p><strong>Establece rutinas saludables:</strong> Mantén una rutina diaria equilibrada que incluya suficiente tiempo para dormir, comer de manera saludable, hacer ejercicio y relajarse. Esto puede ayudar a regular tus niveles de estrés y mejorar tu bienestar general.</p>\n\n<p><strong>');
});

document.getElementById('ansiedad').addEventListener('click', function (event) {
    event.preventDefault();
    mostrarModal('img/afrontando la ansiedad.jpg', '<p><strong>Enfrentar la ansiedad en situaciones específicas:</strong> Si experimentas ansiedad en situaciones particulares, como hablar en público o viajar en avión, considera enfrentarte gradualmente a esas situaciones mediante la exposición gradual. Puedes empezar con pequeños pasos y aumentar gradualmente la exposición a medida que te sientas más cómodo.</p>\n\n<p><strong>Practicar técnicas de relajación:</strong> Dedica tiempo a practicar técnicas de relajación como la respiración profunda, la meditación, el yoga o la visualización guiada. Estas técnicas pueden ayudar a calmar el sistema nervioso y reducir los síntomas de ansiedad.</p>\n\n<p><strong>Desafiar pensamientos negativos:</strong> Identifica y cuestiona pensamientos negativos y catastróficos que puedan estar contribuyendo a tu ansiedad.');
});
